server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://booklog.chl7p9tqzuib.ap-northeast-2.rds.amazonaws.com:3306/booklog
#    url: jdbc:mariadb://localhost:3307/booklog?serverTimezone=Asia/Seoul

    #jdbc:mysql://booklog-db.c4akum70ou2t.ap-northeast-2.rds.amazonaws.com:3306/booklog_db
#    username: root
    username: admin
    #admin
#    password: 1234
    password: song2me1234
    #20000118
  main:
    allow-circular-references: true

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

    security:
      oauth2:
        client:
          registration:
            google:
              client-id: 414665926641-5lm4nmg7a53ted4mo3od94u7oqrbufkc.apps.googleusercontent.com
              client-secret: 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
              scope:
                - profile
                - email
            kakao:
              client-id: 08ca26dee47a95cd81776bdad15aec58
              client-secret: DVEJp8VA36mVFgwz8SwJ32Rde0dEcG6d
              redirect-uri: http://localhost:8080/login/oauth2/code/kakao
              authorization-grant-type: authorization_code
              client-authentication-method: POST
              client-name: kakao
              scope:
                - profile_nickname
                - account_email
              naver:
                client-id: 7kTbI88i6SMJmon6Jd_f
                client-secret: a1NBaeecDK
                redirect-uri: http://localhost:8080/login/oauth2/code/naver
                authorization-grant-type: authorization_code
                client-name: naver
                scope:
                  - name
                  - email
          provider:
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id
            naver:
              authorization-uri: https://nid.naver.com/oauth2.0/authorize
              token-uri: https://nid.naver.com/oauth2.0/token
              user-info-uri: https://openapi.naver.com/v1/nid/me
              user-name-attribute: response
